function compile_MSIQuickView()
addpath('C:\MSIQuickView_code_GIT');
mcc -e 'C:/MSIQuickView_code_GIT/MSI_QuickView.m' ...
    -a 'C:/MSIQuickView_code_GIT/colormaps' ...
    -a 'C:/MSIQuickView_code_GIT/config' ...
    -a 'C:/MSIQuickView_code_GIT/Data Processing' ... 
    -a 'C:/MSIQuickView_code_GIT/Dependencies' ...
    -a 'C:/MSIQuickView_code_GIT/Descriptions' ... 
    -a 'C:/MSIQuickView_code_GIT/Elasticsearch' ... 
    -a 'C:/MSIQuickView_code_GIT/ImageJ' ...
    -a 'C:/MSIQuickView_code_GIT/Images' ... 
    -a 'C:/MSIQuickView_code_GIT/Proven' ... 
    -a 'C:/MSIQuickView_code_GIT/Python' ... 
    -a 'C:/MSIQuickView_code_GIT/UI' ... 
    -a 'C:/MSIQuickView_code_GIT/Usecases' ...
    -d 'C:/Users/thom991/Documents/MATLAB/MSI_QuickView' ...
    -M 'C:/MSIQuickView_code_GIT/Images/Capture100.png'

copyfile('C:\MSIQuickView_code_GIT\Python','C:/Users/thom991/Documents/MATLAB/MSI_QuickView/Python')