function handles = set_default_handles(handles)
handles.sum_of_intensities = [];
handles.down_val = [];
handles.across_val = [];
handles.execs = {};
handles.image_window_to_display_value = 1;
handles.plot_val = 1;
handles.normalize_data_mode = 0;
handles.size_count_limits = 1;
handles.next_sum_folder = 2;
handles.myobj = [];
handles.lower_limit_for_grayscale_color = 0;
handles.higher_limit_for_grayscale_color = 100;
handles.apply_manipulations_to_all = 0;
handles.avg_image_pixels = 0;
handles.instrument_bruker = [];
handles.ext = '.cdf';